// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.unige.idsi.y15.parkfind_roo;

import ch.unige.idsi.y15.parkfind_roo.ParkingVoie;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ParkingVoie_Roo_Configurable {
    
    declare @type: ParkingVoie: @Configurable;
    
}
