// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.unige.idsi.y15.parkingtest1;

import ch.unige.idsi.y15.parkfind_roo.ParkingHandi;
import ch.unige.idsi.y15.parkingtest1.ParkingHandiDataOnDemand;
import ch.unige.idsi.y15.parkingtest1.ParkingHandiIntegrationTest;

import java.util.Iterator;
import java.util.List;

import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;

import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ParkingHandiIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ParkingHandiIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ParkingHandiIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ParkingHandiIntegrationTest: @Transactional;
    
    @Autowired
    ParkingHandiDataOnDemand ParkingHandiIntegrationTest.dod;
    
    @Test
    public void ParkingHandiIntegrationTest.testCountParkingHandis() {
        Assert.assertNotNull("Data on demand for 'ParkingHandi' failed to initialize correctly", dod.getRandomParkingHandi());
        long count = ParkingHandi.countParkingHandis();
        Assert.assertTrue("Counter for 'ParkingHandi' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ParkingHandiIntegrationTest.testFindParkingHandi() {
        ParkingHandi obj = dod.getRandomParkingHandi();
        Assert.assertNotNull("Data on demand for 'ParkingHandi' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ParkingHandi' failed to provide an identifier", id);
        obj = ParkingHandi.findParkingHandi(id);
        Assert.assertNotNull("Find method for 'ParkingHandi' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ParkingHandi' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ParkingHandiIntegrationTest.testFindAllParkingHandis() {
        Assert.assertNotNull("Data on demand for 'ParkingHandi' failed to initialize correctly", dod.getRandomParkingHandi());
        long count = ParkingHandi.countParkingHandis();
        Assert.assertTrue("Too expensive to perform a find all test for 'ParkingHandi', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ParkingHandi> result = ParkingHandi.findAllParkingHandis();
        Assert.assertNotNull("Find all method for 'ParkingHandi' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ParkingHandi' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ParkingHandiIntegrationTest.testFindParkingHandiEntries() {
        Assert.assertNotNull("Data on demand for 'ParkingHandi' failed to initialize correctly", dod.getRandomParkingHandi());
        long count = ParkingHandi.countParkingHandis();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ParkingHandi> result = ParkingHandi.findParkingHandiEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ParkingHandi' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ParkingHandi' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ParkingHandiIntegrationTest.testFlush() {
        ParkingHandi obj = dod.getRandomParkingHandi();
        Assert.assertNotNull("Data on demand for 'ParkingHandi' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ParkingHandi' failed to provide an identifier", id);
        obj = ParkingHandi.findParkingHandi(id);
        Assert.assertNotNull("Find method for 'ParkingHandi' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyParkingHandi(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ParkingHandi' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ParkingHandiIntegrationTest.testMergeUpdate() {
        ParkingHandi obj = dod.getRandomParkingHandi();
        Assert.assertNotNull("Data on demand for 'ParkingHandi' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ParkingHandi' failed to provide an identifier", id);
        obj = ParkingHandi.findParkingHandi(id);
        boolean modified =  dod.modifyParkingHandi(obj);
        Integer currentVersion = obj.getVersion();
        ParkingHandi merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ParkingHandi' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ParkingHandiIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ParkingHandi' failed to initialize correctly", dod.getRandomParkingHandi());
        ParkingHandi obj = dod.getNewTransientParkingHandi(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ParkingHandi' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ParkingHandi' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ParkingHandi' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ParkingHandiIntegrationTest.testRemove() {
        ParkingHandi obj = dod.getRandomParkingHandi();
        Assert.assertNotNull("Data on demand for 'ParkingHandi' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ParkingHandi' failed to provide an identifier", id);
        obj = ParkingHandi.findParkingHandi(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ParkingHandi' with identifier '" + id + "'", ParkingHandi.findParkingHandi(id));
    }
    
}
