// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.unige.idsi.y15.parkingtest1;

import ch.unige.idsi.y15.parkingtest1.ParkingHandiIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ParkingHandiIntegrationTest_Roo_Configurable {
    
    declare @type: ParkingHandiIntegrationTest: @Configurable;
    
}
